table dim_customer

	column customer_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: customer_id

	column customer_name
		dataType: string
		summarizeBy: none
		sourceColumn: customer_name

	column channel
		dataType: string
		summarizeBy: none
		sourceColumn: channel

	column region
		dataType: string
		summarizeBy: none
		sourceColumn: region

	partition dim_customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\dim_customer.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"customer_id", Int64.Type}, {"customer_name", type text}, {"channel", type text}, {"region", type text}})
				in
				    Typed
