table dim_warehouse
	lineageTag: 3c5d6f88-1c78-4e3d-9eec-4885c3ee7434

	column warehouse_id
		dataType: int64
		formatString: 0
		lineageTag: da9b44c9-f633-469c-af3f-f5983f7ea735
		summarizeBy: none
		sourceColumn: warehouse_id

	column warehouse_name
		dataType: string
		lineageTag: 2c78f680-bb4f-426c-8220-ec27b44d525c
		summarizeBy: none
		sourceColumn: warehouse_name

	column region
		dataType: string
		lineageTag: 5e0868b3-c14d-419f-a191-a0c17f7d298e
		summarizeBy: none
		sourceColumn: region

	column city
		dataType: string
		lineageTag: fa7a983e-2fcc-4102-8312-67ab4bc58d54
		summarizeBy: none
		sourceColumn: city

	partition dim_warehouse = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\dim_warehouse.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"warehouse_id", Int64.Type}, {"warehouse_name", type text}, {"region", type text}, {"city", type text}})
				in
				    Typed

