table dim_lot
	lineageTag: 4018b9d0-e432-47d1-94d6-93f1c6a7a320

	column lot_id
		dataType: int64
		formatString: 0
		lineageTag: d1e5dac1-25ff-4182-8c58-7b43382d2135
		summarizeBy: none
		sourceColumn: lot_id

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: d2a50ab4-9a2d-4698-8333-0466c02135cd
		summarizeBy: sum
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column supplier_id
		dataType: int64
		formatString: 0
		lineageTag: 27827f1e-7e7e-4409-867f-974da7227e03
		summarizeBy: none
		sourceColumn: supplier_id

	column warehouse_id
		dataType: int64
		formatString: 0
		lineageTag: 72713c76-87df-4909-bbd8-4bc41fd9fcd3
		summarizeBy: sum
		sourceColumn: warehouse_id

		annotation SummarizationSetBy = Automatic

	column production_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 3de533c4-3d49-4ec7-9c13-a39375229dbc
		summarizeBy: none
		sourceColumn: production_date

		annotation UnderlyingDateTimeDataType = Date

	column received_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: da1404c1-e78a-41ed-b9c7-ce86860e12ae
		summarizeBy: none
		sourceColumn: received_date

		annotation UnderlyingDateTimeDataType = Date

	column expiry_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: f33e6044-edcf-49a9-904c-7b2fb43d36b1
		summarizeBy: none
		sourceColumn: expiry_date

		annotation UnderlyingDateTimeDataType = Date

	partition dim_lot = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\dim_lot.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"lot_id", Int64.Type}, {"product_id", Int64.Type}, {"supplier_id", Int64.Type}, {"warehouse_id", Int64.Type}, {"production_date", type date}, {"received_date", type date}, {"expiry_date", type date}})
				in
				    Typed

