table dim_lot

	column lot_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: lot_id

	column product_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: product_id

	column supplier_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: supplier_id

	column warehouse_id
		dataType: int64
		formatString: 0
		summarizeBy: none
		sourceColumn: warehouse_id

	column production_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: production_date

	column received_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: received_date

	column expiry_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		summarizeBy: none
		sourceColumn: expiry_date

	partition dim_lot = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataPath & "\dim_lot.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"lot_id", Int64.Type}, {"product_id", Int64.Type}, {"supplier_id", Int64.Type}, {"warehouse_id", Int64.Type}, {"production_date", type date}, {"received_date", type date}, {"expiry_date", type date}})
				in
				    Typed
