table fact_inventory
	lineageTag: b065bdae-9990-4e00-8831-3d5afbd854fa

	column snapshot_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: e71c0f23-1502-44c9-aad6-88ec2e24525e
		summarizeBy: none
		sourceColumn: snapshot_date

		annotation UnderlyingDateTimeDataType = Date

	column lot_id
		dataType: int64
		formatString: 0
		lineageTag: 03b517fe-82dd-466f-b23a-eb350b635774
		summarizeBy: none
		sourceColumn: lot_id

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: 300ddd49-a310-47b5-861d-be71158e0dc0
		summarizeBy: none
		sourceColumn: product_id

	column warehouse_id
		dataType: int64
		formatString: 0
		lineageTag: 59060e27-4fff-4cc6-8579-973b258bf38c
		summarizeBy: none
		sourceColumn: warehouse_id

	column qty_on_hand
		dataType: double
		lineageTag: 5d54a6c9-6d83-48e7-96c5-6c1208b3d7e6
		summarizeBy: sum
		sourceColumn: qty_on_hand

	column days_until_expiry
		dataType: int64
		formatString: 0
		lineageTag: 4e0bb4e6-12b8-447c-8949-ac234b50a0f6
		summarizeBy: none
		sourceColumn: days_until_expiry

	column expiry_risk_flag
		dataType: string
		lineageTag: 80541712-1622-4ad4-960a-a06f8459f8b9
		summarizeBy: none
		sourceColumn: expiry_risk_flag

	column inventory_value
		dataType: double
		lineageTag: 1d25548f-ea3b-469d-86fc-e29095c67adf
		summarizeBy: sum
		sourceColumn: inventory_value

	partition fact_inventory = m
		mode: import
		source =
				let
				    // Lot expiry and product cost loaded inline (not by referencing sibling
				    // queries) so this query never mixes a direct data-source access with a
				    // query reference — that combination trips Power Query's privacy firewall.
				    LotRaw = Csv.Document(File.Contents(DataPath & "\dim_lot.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    LotPromoted = Table.PromoteHeaders(LotRaw, [PromoteAllScalars = true]),
				    LotExpiry = Table.TransformColumnTypes(Table.SelectColumns(LotPromoted, {"lot_id", "expiry_date"}), {{"lot_id", Int64.Type}, {"expiry_date", type date}}),
				    ProductRaw = Csv.Document(File.Contents(DataPath & "\dim_product.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    ProductPromoted = Table.PromoteHeaders(ProductRaw, [PromoteAllScalars = true]),
				    ProductCost = Table.TransformColumnTypes(Table.SelectColumns(ProductPromoted, {"product_id", "unit_cost"}), {{"product_id", Int64.Type}, {"unit_cost", type number}}),
				    Source = Csv.Document(File.Contents(DataPath & "\fact_inventory_snapshot.csv"), [Delimiter = ",", Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"snapshot_date", type date}, {"lot_id", Int64.Type}, {"product_id", Int64.Type}, {"warehouse_id", Int64.Type}, {"qty_on_hand", type number}}),
				    // Silver rule: FEFO expiry risk banding from the lot's expiry date
				    MergedLot = Table.NestedJoin(Typed, {"lot_id"}, LotExpiry, {"lot_id"}, "lot", JoinKind.Inner),
				    ExpandedLot = Table.ExpandTableColumn(MergedLot, "lot", {"expiry_date"}, {"expiry_date"}),
				    AddedDays = Table.AddColumn(ExpandedLot, "days_until_expiry", each Duration.Days([expiry_date] - [snapshot_date]), Int64.Type),
				    AddedRisk = Table.AddColumn(AddedDays, "expiry_risk_flag", each if [days_until_expiry] <= 2 then "Critical" else if [days_until_expiry] <= 5 then "Warning" else "OK", type text),
				    MergedProduct = Table.NestedJoin(AddedRisk, {"product_id"}, ProductCost, {"product_id"}, "product", JoinKind.Inner),
				    ExpandedProduct = Table.ExpandTableColumn(MergedProduct, "product", {"unit_cost"}, {"unit_cost"}),
				    AddedValue = Table.AddColumn(ExpandedProduct, "inventory_value", each Number.Round([qty_on_hand] * [unit_cost], 2), type number),
				    Cleaned = Table.RemoveColumns(AddedValue, {"expiry_date", "unit_cost"})
				in
				    Cleaned

